/**
 * Builds public/vendor/lucide.min.js containing ONLY the icons this site uses.
 * The full lucide UMD bundle is ~348 KB; the subset is ~8 KB.
 *
 * Icons referenced as data-lucide="..." in markup are discovered automatically.
 * Icons set at runtime (e.g. the theme toggle swapping sun/moon) cannot be, so
 * they are listed in DYNAMIC below — add to it if you introduce another.
 */
import { readFileSync, writeFileSync, mkdirSync, readdirSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import path from 'node:path';

const DYNAMIC = ['sun', 'moon', 'menu', 'x'];
const SOURCES = [
  ...readdirSync('pages').filter(f => f.endsWith('.html')).map(f => path.join('pages', f)),
  ...readdirSync('public').filter(f => f.endsWith('.js')).map(f => path.join('public', f)),
  'server.ts',
];

const found = new Set(DYNAMIC);
for (const file of SOURCES) {
  const text = readFileSync(file, 'utf8');
  for (const m of text.matchAll(/data-lucide="([a-z0-9-]+)"/g)) found.add(m[1]);
}

const used = [...found].sort();
const pascal = s => s.split('-').map(p => p[0].toUpperCase() + p.slice(1)).join('');
const names = used.map(pascal);

mkdirSync('src', { recursive: true });
writeFileSync('src/lucide.subset.js', `// GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createIcons as _createIcons, ${names.join(', ')} } from 'lucide';

export const icons = { ${names.join(', ')} };

// shared.js calls lucide.createIcons() with no arguments, so default the set.
export function createIcons(options = {}) {
  return _createIcons({ icons, ...options });
}
`);

mkdirSync('public/vendor', { recursive: true });
execFileSync(path.join('node_modules', '.bin', 'esbuild'), [
  'src/lucide.subset.js', '--bundle', '--minify', '--format=iife',
  '--global-name=lucide', '--outfile=public/vendor/lucide.min.js',
], { stdio: 'inherit' });

console.log(`lucide subset: ${used.length} icons — ${used.join(' ')}`);
