// GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createIcons as _createIcons, ArrowRight, Award, Briefcase, Calendar, CheckCircle2, Cpu, EyeOff, Layers, Linkedin, Lock, Mail, MapPin, Menu, Mic, Moon, Send, Server, ShieldAlert, ShieldCheck, Sun, TrendingUp, Users, Video, X } from 'lucide';

export const icons = { ArrowRight, Award, Briefcase, Calendar, CheckCircle2, Cpu, EyeOff, Layers, Linkedin, Lock, Mail, MapPin, Menu, Mic, Moon, Send, Server, ShieldAlert, ShieldCheck, Sun, TrendingUp, Users, Video, X };

// shared.js calls lucide.createIcons() with no arguments, so default the set.
export function createIcons(options = {}) {
  return _createIcons({ icons, ...options });
}
